/**
 * What this agent prints, per locale: the runner's words for it, the lines an
 * order reads as, the one message per outcome the customer receives, and the
 * words pricing and the order tools write (the cart's issues, the gate's
 * refusal details, an order's status). Every key exists in both entries (`npm
 * run check`).
 *
 * The issue CODES (`coupon_unknown`, `quantity_above_stock`) and the reason
 * codes are machine words and are the same in every locale; a test reads the
 * code, a person reads the message. The details never quote the envelope's
 * numbers or a cost, in either language (checkout §5.6).
 */
import type { LocaleTable } from "@codespar/agent-core";
import type { KitStrings } from "@codespar/agent-runtime";

const pt = {
  mandateWord: "política",
  receiptWord: "pedido",
  intro: 'Você é o cliente. Diga o que quer ("oi, sou a Marina, quero o pacote de dez aulas e uma avaliação inicial"). Ctrl+D ou "sair" encerra.',
  prompt: "cliente> ",
  approveQuestion: "  [atendente] Confirmar este pedido? [s/N] ",
  uncertainDispatch: "  desfecho desconhecido no trilho; rode `npm run resume` para reconciliar (nunca repita a emissão)",
  notAuthorized: "a política não autoriza",
  waitingForPayer: (round: number) => `  aguardando o pagamento... (${round} consultas)`,

  order: "pedido",
  customerLine: (customer: string, cart: string | undefined) => `cliente ${customer}${cart ? `, carrinho ${cart}` : ""}`,
  lineDiscount: (pct: number) => ` (desconto ${pct}%)`,
  coupon: (code: string) => `cupom ${code}`,
  orderDiscount: "desconto no pedido",
  cartLines: (count: number) => `${count} linha(s)`,
  charge: "cobrança",
  paidOrder: "pedido pago",
  invoiceDocument: (id: string) => ` — documento ${id}`,
  orderOf: (total: string) => `Pedido de ${total}`,

  toldSettled: (chargeIds: string) => `Recebemos, pedido confirmado! Obrigado. (${chargeIds})`,
  toldExpired: "A cobrança venceu sem pagamento. Se quiser, emito uma nova para o mesmo pedido.",
  toldCancelled: "A cobrança foi cancelada. Nada foi pago.",
  toldAmbiguous: "A cobrança deste pedido já foi emitida e estamos conferindo a situação dela. Não pague de novo; te aviso assim que estiver conferida.",
  toldFailed: (reason: string | undefined) => `Não consegui emitir a cobrança (${reason ?? "falha no trilho"}). Nada foi cobrado.`,
  toldDenied: (reason: string | undefined) => `Não consigo fechar o pedido nesses termos (${reason ?? "recusado"}).`,
  toldUndecided: (why: string) => `O pedido expirou sem confirmação (${why}).`,

  orderApproved: "pedido confirmado; a cobrança sai quando o cliente pedir (action=issue)",
  orderCartChanged: "o carrinho mudou depois da confirmação; o pedido voltou para o atendente",
  orderAwaitingAttendant: "aguardando o atendente confirmar o pedido",
  orderIssued: "cobrança emitida; aguardando o pagamento",
  orderUncertain: "desfecho da emissão desconhecido; nada será reemitido",
  orderPaid: "pago",
  noOrderForCart: (cartId: string) => `o carrinho ${cartId} ainda não virou pedido`,
  noOrder: "nenhum pedido nesta conversa",
  alreadyOrdered: (executionId: string) => `este carrinho já é o pedido ${executionId}; nada novo foi criado`,
  noCart: "nenhum carrinho aberto nesta conversa; cart_update abre um",

  totalItems: "Itens",
  totalItemsDiscount: "Descontos nos itens",
  totalSubtotal: "Subtotal",
  totalOrderDiscount: "Desconto do pedido",
  totalTotal: "Total",
  lineValue: "Valor",
  lineDiscountTotal: "Desconto",
  lineTotal: "Total da linha",

  issuePriceNotInput: "o preço vem do catálogo da loja; a linha foi recusada inteira",
  issueSkuUnknown: (sku: string) => `não temos ${sku || "esse item"} no catálogo`,
  issueUnavailable: (title: string) => `${title} está indisponível`,
  issueQuantityInvalid: (max: number) => `quantidade deve ser um inteiro de 1 a ${max}`,
  issueDuplicateSku: (sku: string) => `${sku} aparece mais de uma vez; uma linha por item, com a quantidade total`,
  issueAboveStock: (stock: number, title: string) => `só há ${stock} de ${title}`,
  issueCouponUnknown: (code: string) => `o cupom ${code} não existe nesta loja`,
  issueCouponExpired: (code: string) => `o cupom ${code} expirou`,
  issueCouponMinimum: (code: string, minimum: string) => `o cupom ${code} vale para pedidos a partir de ${minimum}`,

  outsideServiceHours: (window: string, timezone: string, clock: string) => `fora do horário de atendimento (${window} ${timezone}); agora são ${clock}`,
  gateOneItem: "um pedido é uma cobrança: um item, cujo valor é o total do carrinho",
  gateNoCart: "um pedido nasce de um carrinho; esta execução não nomeia nenhum",
  gateCartMissing: (ref: string) => `o carrinho ${ref} não existe neste estado`,
  gateCartChanged: "o pedido não corresponde ao carrinho atual; o carrinho mudou depois",
  gateCartEmpty: "carrinho vazio",
  gateCartIssues: (codes: string) => `o carrinho tem pendências (${codes})`,
  gateTotalMismatch: (charged: number, cart: number) => `o pedido cobra ${charged} e o carrinho soma ${cart}`,
  gateNotForSale: (sku: string) => `${sku} não está à venda`,
  gateNotListPrice: (sku: string) => `${sku} não está pelo preço de tabela`,
  gateQuantity: (sku: string) => `quantidade de ${sku} fora do permitido`,
  gateLineDiscount: (sku: string) => `desconto em ${sku} acima do que a política da loja permite`,
  gateLineMargin: (sku: string) => `${sku} ficaria abaixo do piso de margem da loja`,
  gateOrderDiscount: "desconto no pedido acima do que a política da loja permite",
  gateCouponAndDiscount: "cupom e desconto negociado não se somam",
  gateCouponInvalid: (code: string) => `o cupom ${code} não vale para este pedido`,
  gateOrderMargin: "o pedido ficaria abaixo do piso de margem da loja",
  gateTicket: (total: string) => `pedido de ${total} acima do ticket máximo da loja`,
  gateNoDueDate: "a cobrança do pedido não tem vencimento",
  gateDueOutsideWindow: (due: string, today: string, last: string) => `vencimento ${due} fora da janela da loja (de ${today} até ${last})`,
};

export const STRINGS: LocaleTable<typeof pt & KitStrings> = {
  "pt-BR": pt,
  en: {
    mandateWord: "policy",
    receiptWord: "order",
    intro: 'You are the customer. Say what you want ("hi, I am Marina, I want the ten-class pack and an initial assessment"). Ctrl+D or "exit" ends.',
    prompt: "customer> ",
    approveQuestion: "  [attendant] Confirm this order? [y/N] ",
    uncertainDispatch: "  outcome unknown on the rail; run `npm run resume` to reconcile (never repeat the issuance)",
    notAuthorized: "the policy does not authorize it",
    waitingForPayer: (round) => `  waiting for the payment... (${round} looks)`,

    order: "order",
    customerLine: (customer, cart) => `customer ${customer}${cart ? `, cart ${cart}` : ""}`,
    lineDiscount: (pct) => ` (discount ${pct}%)`,
    coupon: (code) => `coupon ${code}`,
    orderDiscount: "order discount",
    cartLines: (count) => `${count} line(s)`,
    charge: "charge",
    paidOrder: "paid order",
    invoiceDocument: (id) => ` — document ${id}`,
    orderOf: (total) => `Order of ${total}`,

    toldSettled: (chargeIds) => `Payment received, order confirmed! Thank you. (${chargeIds})`,
    toldExpired: "The charge reached its due date unpaid. If you like, I can issue a new one for the same order.",
    toldCancelled: "The charge was cancelled. Nothing was paid.",
    toldAmbiguous: "The charge for this order was already issued and we are checking where it stands. Do not pay again; I will let you know as soon as it is checked.",
    toldFailed: (reason) => `I could not issue the charge (${reason ?? "rail failure"}). Nothing was charged.`,
    toldDenied: (reason) => `I cannot close the order on those terms (${reason ?? "refused"}).`,
    toldUndecided: (why) => `The order expired without a confirmation (${why}).`,

    orderApproved: "order confirmed; the charge goes out when the customer asks for it (action=issue)",
    orderCartChanged: "the cart changed after the confirmation; the order went back to the attendant",
    orderAwaitingAttendant: "waiting for the attendant to confirm the order",
    orderIssued: "charge issued; waiting for the payment",
    orderUncertain: "outcome of the issuance unknown; nothing will be re-issued",
    orderPaid: "paid",
    noOrderForCart: (cartId) => `cart ${cartId} has not become an order yet`,
    noOrder: "no order in this conversation",
    alreadyOrdered: (executionId) => `this cart is already order ${executionId}; nothing new was created`,
    noCart: "no cart open in this conversation; cart_update opens one",

    totalItems: "Items",
    totalItemsDiscount: "Item discounts",
    totalSubtotal: "Subtotal",
    totalOrderDiscount: "Order discount",
    totalTotal: "Total",
    lineValue: "Amount",
    lineDiscountTotal: "Discount",
    lineTotal: "Line total",

    issuePriceNotInput: "the price comes from the store's catalog; the whole line was refused",
    issueSkuUnknown: (sku) => `we do not have ${sku || "that item"} in the catalog`,
    issueUnavailable: (title) => `${title} is unavailable`,
    issueQuantityInvalid: (max) => `the quantity must be a whole number from 1 to ${max}`,
    issueDuplicateSku: (sku) => `${sku} appears more than once; one line per item, with the total quantity`,
    issueAboveStock: (stock, title) => `there are only ${stock} of ${title}`,
    issueCouponUnknown: (code) => `coupon ${code} does not exist in this store`,
    issueCouponExpired: (code) => `coupon ${code} has expired`,
    issueCouponMinimum: (code, minimum) => `coupon ${code} applies to orders from ${minimum}`,

    outsideServiceHours: (window, timezone, clock) => `outside service hours (${window} ${timezone}); it is ${clock} now`,
    gateOneItem: "an order is one charge: one item, whose amount is the cart's total",
    gateNoCart: "an order is born from a cart; this execution names none",
    gateCartMissing: (ref) => `cart ${ref} does not exist in this state`,
    gateCartChanged: "the order does not match the current cart; the cart changed afterwards",
    gateCartEmpty: "empty cart",
    gateCartIssues: (codes) => `the cart has pending issues (${codes})`,
    gateTotalMismatch: (charged, cart) => `the order charges ${charged} and the cart adds up to ${cart}`,
    gateNotForSale: (sku) => `${sku} is not for sale`,
    gateNotListPrice: (sku) => `${sku} is not at the list price`,
    gateQuantity: (sku) => `the quantity of ${sku} is outside what is allowed`,
    gateLineDiscount: (sku) => `the discount on ${sku} is above what the store's policy allows`,
    gateLineMargin: (sku) => `${sku} would fall below the store's margin floor`,
    gateOrderDiscount: "the order discount is above what the store's policy allows",
    gateCouponAndDiscount: "a coupon and a negotiated discount do not add up",
    gateCouponInvalid: (code) => `coupon ${code} does not apply to this order`,
    gateOrderMargin: "the order would fall below the store's margin floor",
    gateTicket: (total) => `an order of ${total} is above the store's maximum ticket`,
    gateNoDueDate: "the order's charge has no due date",
    gateDueOutsideWindow: (due, today, last) => `due date ${due} is outside the store's window (from ${today} to ${last})`,
  },
};
